### ISSUE TITLE
Check in postinst fails to detect pre-existing records in /etc/hosts

### ISSUE THREAD

**Issue by cluck** [Games-Crack/NoNagProxmox#1]
The check for a pre-existing record in /etc/hosts in [scripts/postinst](https://github.com/Games-Crack/NoNagProxmox/blob/f0ae5d363cb1a44920f501390470fbac52538841/scripts/postinst#L29C5-L29C46) doesn't work as expected: it tells grep to match whole lines that read just like the fqdn, which wouldn't be a valid hosts line and is also not what would be added following this check.

May I propose this line instead:
```
grep -Fim1 shop.maurer-it.com /etc/hosts || echo -e "\n# Added by NoNagProxmox\n127.0.0.1\tshop.maurer-it.com\n" >>/etc/hosts
```

**Comment by Games-Crack** [comment]
I've silenced it by adding `` &>/dev/null `` to the grep portion.

I Will add that to the next build, my Proxmox Server has a mayor outage right now, i will build the fix ASAP

More Issues/PR's Welcome & Thank you!
